name: pass non-unit tests

on:
  push:
    branches: [main]
    paths:
      - '**.cs'
      - '**.csproj'
  pull_request:
    branches: [main]
    paths:
      - '**.cs'
      - '**.csproj'

env:
  DOTNET_VERSION: '9.0.300' # The .NET SDK version to use

jobs:
  pass-backend-functional-tests:

    name: Pass backend functional tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Test backend with functional tests
      run: dotnet run --project backend/test/SimplifiedDnd.WebApi.FunctionalTests --explicit=on
        
  pass-database-integration-tests:

    name: Pass database integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Test database with integration tests
        run: dotnet run --project backend/test/SimplifiedDnd.Database.IntegrationTests --explicit=on